/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simbolos;

import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell E5420
 */
public class Menu extends javax.swing.JFrame {

    JFileChooser selec=new JFileChooser();
    File archivo;
    Abrir_archivo marchi=new Abrir_archivo();
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Area_entrada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Area_contador = new javax.swing.JTextArea();
        bt_analizar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_salida = new javax.swing.JList<>();
        btn_acercade = new javax.swing.JButton();
        btn_abrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Area_entrada.setColumns(20);
        Area_entrada.setRows(5);
        jScrollPane1.setViewportView(Area_entrada);

        Area_contador.setColumns(20);
        Area_contador.setRows(5);
        jScrollPane3.setViewportView(Area_contador);

        bt_analizar.setText("Analizar");
        bt_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_analizarActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(list_salida);

        btn_acercade.setText("Acerca De");
        btn_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acercadeActionPerformed(evt);
            }
        });

        btn_abrir.setText("Abrir");
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_acercade)
                    .addComponent(bt_analizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_abrir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btn_abrir)
                        .addGap(32, 32, 32)
                        .addComponent(bt_analizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_acercade)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_analizarActionPerformed
        
      DefaultListModel listMod = new DefaultListModel();
        String entrada=Area_entrada.getText();
        char[] cadena=entrada.toCharArray();
        int letters=0;
        int symbol=0;
        int numbers=0;
        
        for(int i=0;i<cadena.length;i++){
         //----Reconoce todos los distintos tipos de signos--------   
            if((cadena[i]>=33 && cadena[i]<=47) ||(cadena[i]>=58 && cadena[i]<=64)||(cadena[i]>=91 && cadena[i]<=96)||(cadena[i]>=123 && cadena[i]<=125)){
               listMod.addElement(Character.toString(cadena[i])+" ------>"+"Signo");
               list_salida.setModel(listMod);
               symbol++;
            }
         //----Reconoce todos las letras-------------------------   
            if((cadena[i]>=65 && cadena[i]<=90) ||(cadena[i]>=97 && cadena[i]<=123)){
               listMod.addElement(Character.toString(cadena[i])+" ------>"+"Letra");
               list_salida.setModel(listMod);
               letters++;
            }
          //----Reconoce todos las Numeros-------------------------   
            if(cadena[i]>=48 && cadena[i]<=57){
               listMod.addElement(Character.toString(cadena[i])+" ------>"+"Digito");
               list_salida.setModel(listMod);
               numbers++;
            }
          //----Elimina espacios, tabuladores, saltos de linea-------------------------   
            if(cadena[i]==32 || cadena[i]==9 || cadena[i]==10){
               cadena[i]=cadena[i+1];  
            }
        }
        
        Area_contador.setText("No.Letras: "+Integer.toString(letters)+"\n"
                             +"No.Digitos: "+Integer.toString(numbers)+"\n"
                             +"No.Simbolos: "+Integer.toString(symbol));
        
        
        
    }//GEN-LAST:event_bt_analizarActionPerformed

    private void btn_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acercadeActionPerformed
        JOptionPane.showMessageDialog(this, "UNIVERSIDAD SAN CARLOS DE GUATEMALA \n"+
                                            "Brian Steve Morales Samayoa \n"+
                                            "Lenguajes formales y de programacion Seccion A \n"+
                                            "Vacaciones Junio 2018");
    }//GEN-LAST:event_btn_acercadeActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
         if (selec.showDialog(this, "Abrir archivo")== JFileChooser.APPROVE_OPTION){
                 archivo=selec.getSelectedFile();
                if(archivo.getName().endsWith("lfp")){
                    String contenido=marchi.Abrir(archivo);
                    Area_entrada.setText(contenido);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "NO es un archivo .lfp");
                }
                
            }
    }//GEN-LAST:event_btn_abrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area_contador;
    private javax.swing.JTextArea Area_entrada;
    private javax.swing.JButton bt_analizar;
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_acercade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> list_salida;
    // End of variables declaration//GEN-END:variables
    
}
